name: Sync Grammar Points

on:
  push:
    paths:
      - 'grammar/**'
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Create Grammar Points JSON
        run: |
          mkdir -p public
          node scripts/generate-grammar.js
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public