name: Sync Grammar Points

on:
  push:
    paths:
      - 'grammar/**'

jobs:
  sync-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Update Index
        run: |
          python .github/scripts/update_index.py
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.md
          git commit -m "Auto update index" || echo "No changes to commit"
          git push
