name: Sync Grammar Points

on:
  push:
    branches: [ main ]
    paths:
      - 'grammar/**'
      - 'scripts/**'
      - 'public/**'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Prepare Directory
        run: |
          mkdir -p _site
          cp -r public/* _site/ || true
      
      - name: Generate Grammar Data
        run: |
          node scripts/generate-grammar.js
          ls -la _site/
          cat _site/grammar-points.json
      
      - name: Update Index
        run: |
          node scripts/update-index.js
          cp grammar/index.md _site/
      
      - name: Debug Directory
        run: |
          echo "Contents of _site directory:"
          ls -la _site/
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site