name: Sync Grammar Points

on:
  push:
    branches: [ main ]
    paths:
      - 'grammar/**'
      - 'scripts/**'
      - 'public/**'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Create Output Directory
        run: |
          mkdir -p _site
          cp -r public/* _site/
      
      - name: Update Index and Generate JSON
        run: |
          # First update the index
          node scripts/update-index.js
          # Then generate the JSON file
          node scripts/generate-grammar.js
          # Copy the generated JSON to site directory
          cat _site/grammar-points.json
          # Also commit the updated index back to main branch
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add grammar/index.md
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "Update index.md [skip ci]" && 
            git push
          )
          
      - name: Copy Grammar Files
        run: |
          # Copy grammar files for reference
          mkdir -p _site/grammar
          cp grammar/*.md _site/grammar/
          
      - name: Debug Directory
        run: |
          echo "Contents of _site directory:"
          ls -la _site/
          echo "Contents of _site/grammar directory:"
          ls -la _site/grammar/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site