name: Update Grammar Index

on:
  # Manual trigger
  workflow_dispatch:
  # Auto trigger
  push:
    branches:
      - refactor/grammar-restructure
    paths:
      - 'grammar/**/*.md'
      - 'scripts/**/*.js'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: |
          echo "Repository contents:"
          ls -R

      - name: Validate workflow
        run: |
          if [ ! -d "grammar" ]; then
            echo "Error: grammar directory not found"
            exit 1
          fi
          if [ ! -d "scripts" ]; then
            echo "Error: scripts directory not found"
            exit 1
          fi
          echo "Basic directory structure validated"

  update-index:
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          echo "Current directory:" $(pwd)
          echo "Directory contents:" $(ls)
          npm install || echo "npm install failed with $?"

      - name: Debug environment
        run: |
          echo "Node version:" $(node --version)
          echo "NPM version:" $(npm --version)
          echo "Package.json contents:"
          cat package.json
          echo "\nInstalled packages:"
          npm list || true

      - name: Update index
        run: node scripts/update_grammar_index.js || echo "Index update failed with $?"

      - name: Check changes
        run: |
          git status
          git diff

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "chore: update grammar index" || echo "No changes to commit"
          git push || echo "Push failed with $?"