name: Update Grammar Index

on:
  push:
    paths:
      - 'grammar/**/*.md'
    branches:
      - 'refactor/grammar-restructure'

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: refactor/grammar-restructure
          fetch-depth: 0
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install gray-matter
          npm install glob
          
      - name: Update Index and JSON
        run: |
          node .github/scripts/update-grammar-index.js
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add grammar/index.md
          git add grammar-points.json
          git commit -m "Update grammar index and JSON" || echo "No changes to commit"
          git push
