name: Update Grammar Index

on:
  push:
    branches: [ main, refactor/grammar-restructure ]
    paths:
      - 'grammar/**/*.md'
      - 'scripts/update_grammar_index.js'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm init -y
        npm install

    - name: Run index generator
      run: node scripts/update_grammar_index.js

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add grammar/index.md docs/grammar-points.json
        git diff --staged --quiet || git commit -m "chore: update grammar index [skip ci]"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
