name: Update Grammar Index

on:
  push:
    branches:
      - refactor/grammar-restructure
    paths:
      - 'grammar/**/*.md'

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update timestamp
        run: |
          echo "# Grammar Index" > grammar/index.md
          echo "Last updated: $(date -u)" >> grammar/index.md
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add grammar/index.md
          git commit -m "Update index timestamp"
          git push